name: API Tests

on:
  push:
    branches: [main]

jobs:
  run-conduit-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: 24
    
      - name: Install dependencies
        run: npm ci

      - name: Run Playwright API tests
        run: npx playwright test